export const BEETROOT_JETTON_MASTER_ADDRESS = "kQCRdFGLPq5J6lSMRPvlOUakwS-35vzsRiGjFo1QHDiDLqkX";
export const USDT_JETTON_MASTER_ADDRESS = "kQBxPxYRD9IOrnIEQysG7D9enWnxg8AGx-wUdcA55mxaKdTK";
export const MAIN_SC_ADDRESS = "kQDKUeeaklszSCSLwRYzH1wf6ExySd2-GSE3B9Nzo0VXBe66";
export const TESTNET_CHAIN_ID = "-3";