name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Archive dist folder
        run: tar -czf dist.tar.gz dist

      - name: Copy and Deploy to Server
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          set -e

          mkdir -p ~/.ssh
          echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "SSH key setup completed"

          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          echo "Added $SERVER_IP to known hosts"

          echo "Testing SSH connection to server"
          ssh -v -o StrictHostKeyChecking=no www@$SERVER_IP "echo 'SSH connection successful'" || { echo "SSH connection failed"; exit 1; }

          echo "Removing dist-old and renaming dist to dist-old on server"
          ssh -v www@$SERVER_IP "
            sudo rm -rf ../../var/www/dist-old &&
            sudo mv ../../var/www/dist /var/www/dist-old
          " || { echo "Failed to modify folders on server"; exit 1; }

          echo "Transferring dist.tar.gz to server"
          scp -v dist.tar.gz www@$SERVER_IP:/var/www || { echo "Failed to transfer dist.tar.gz"; exit 1; }

          echo "Deploying new dist and restarting Nginx"
          ssh -v www@$SERVER_IP "
            cd ../../var/www &&
            tar -xzf dist.tar.gz &&
            sudo rm dist.tar.gz &&
            sudo systemctl restart nginx
          " || { echo "Failed to deploy or restart Nginx"; exit 1; }
