name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Prepare SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        run: |
          sudo apt-get update
          sudo apt-get install -y expect

          cat > /tmp/add_ssh_key.exp <<EOL
          #!/usr/bin/expect -f
          set timeout -1
          spawn ssh-add ~/.ssh/id_ed25519
          expect "Enter passphrase"
          send "$env(SSH_PASSPHRASE)\r"
          expect eof
          EOL

          mkdir -p ~/.ssh
          echo -e "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          eval "$(ssh-agent -s)"

          chmod +x /tmp/add_ssh_key.exp

          /usr/bin/expect /tmp/add_ssh_key.exp || {
            echo "Failed to add SSH key"
            exit 1
          }

          ssh-keygen -y -f ~/.ssh/id_ed25519 || {
            echo "Invalid SSH Ed25519 key format"
            exit 1
          }

      - name: Deploy
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          ssh-add -l 

          ssh-keyscan -p "$SSH_PORT" -H "$SERVER_IP" >> ~/.ssh/known_hosts

          ssh \
            -p "$SSH_PORT" \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            www@$SERVER_IP "hostname" || {
            echo "SSH connection failed"
            exit 1
          }

          scp \
            -P "$SSH_PORT" \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            dist.tar.gz www@$SERVER_IP:/var/www || {
            echo "File transfer failed"
            exit 1
          }
