name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Archive dist folder
        run: tar -czf dist.tar.gz dist

      - name: Copy files to server
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

          ssh www@$SERVER_IP "
            sudo rm -rf /var/www/dist-old &&
            sudo mv /var/www/dist /var/www/dist-old
          "
          scp dist.tar.gz www@$SERVER_IP:/var/www
          ssh www@$SERVER_IP "
            cd /var/www &&
            tar -xzf dist.tar.gz &&
            sudo rm dist.tar.gz &&
            sudo systemctl restart nginx
          "
