name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Prepare SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        run: |
          set -x

          echo "SSH_KEY length: ${#SSH_KEY}"
          echo "SSH_PASSPHRASE length: ${#SSH_PASSPHRASE}"

          mkdir -p /home/runner/.ssh
          chmod 700 /home/runner/.ssh

          echo -e "$SSH_KEY" > /home/runner/.ssh/id_ed25519

          ls -l /home/runner/.ssh/id_ed25519
          cat /home/runner/.ssh/id_ed25519

          chmod 600 /home/runner/.ssh/id_ed25519

          eval "$(ssh-agent -s)"

          ssh-add /home/runner/.ssh/id_ed25519 <<< "$SSH_PASSPHRASE" || {
            echo "Failed to add SSH key"
            exit 1
          }

          ssh-keygen -y -f /home/runner/.ssh/id_ed25519

      - name: Deploy
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          ssh-add -l 

          ssh-keyscan -p "$SSH_PORT" -H "$SERVER_IP" >> ~/.ssh/known_hosts

          ssh \
            -p "$SSH_PORT" \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            www@$SERVER_IP "hostname" || {
            echo "SSH connection failed"
            exit 1
          }

          scp \
            -P "$SSH_PORT" \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            dist.tar.gz www@$SERVER_IP:/var/www || {
            echo "File transfer failed"
            exit 1
          }
